name: Build Docker Images

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]

concurrency:
  group: docker-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['web', 'docs']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hmacr-monorepo/${{ matrix.service }}
          tags: |
            type=ref,prefix=pr,format=short

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./apps/${{ matrix.service }}
          file: ./apps/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}